package de.lhns.mcdp.core;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashSet;
import java.util.List;

/**
 * Defensive helper for platform adapters: given the per-mod modPaths set we're about to feed
 * into a {@link ModClassLoader}, append {@code build/mcdp-bridges/classes} if it exists on
 * disk relative to any entry but isn't already on the list.
 *
 * <p>Background: bridge impl classes live in a sibling {@code <bridgePackage>_impl} package
 * (ADR-0021 errata), loaded child-first by {@code ModClassLoader}. They're emitted into
 * {@code build/mcdp-bridges/classes/} by the gradle plugin's codegen task. The plugin
 * registers that dir via {@code main.output.dir(...)} so it appears in
 * {@code main.getOutput().getFiles()} and lands in the manifest's {@code dev_roots}.
 *
 * <p>Two failure modes for that registration:
 * <ol>
 *   <li>Loom/MDG can re-root the source set after our plugin's apply block runs.</li>
 *   <li>A consumer's manifest may have been generated by an older plugin version that didn't
 *       emit {@code dev_roots} at all.</li>
 * </ol>
 *
 * <p>Either way, if the bridge output dir isn't on the per-mod loader's URL list, impls fall
 * through to the parent classloader (Knot / ModuleClassLoader) and pull mod-private types
 * (Scala stdlib, mod's own classes) onto the wrong loader. This helper restores the safety
 * net the old {@code expandDevRoots} walk had before commit {@code 144db48}.
 */
public final class DevRootSafetyNet {

    private static final String BRIDGE_REL_PATH = "mcdp-bridges/classes";

    private DevRootSafetyNet() {}

    /**
     * Returns a new list = {@code modPaths} with {@code build/mcdp-bridges/classes} appended
     * if a sibling {@code build/} dir is reachable from any entry and contains the bridge
     * output. Idempotent — never duplicates an entry already on the input.
     *
     * <p>Two layouts handled:
     * <ul>
     *   <li>Source-set output dir like {@code <project>/build/classes/java/main} →
     *       walks up to {@code <project>/build} and appends {@code build/mcdp-bridges/classes}.</li>
     *   <li>Resource dir like {@code <project>/build/resources/main} → same walk-up.</li>
     * </ul>
     * Jar-fs roots and arbitrary other paths are left untouched.
     */
    public static List<Path> appendBridgeClassesIfPresent(List<Path> modPaths) {
        LinkedHashSet<Path> out = new LinkedHashSet<>(modPaths);
        for (Path p : modPaths) {
            Path bridge = bridgeDirFor(p);
            if (bridge != null && Files.isDirectory(bridge)) {
                out.add(bridge);
            }
        }
        return List.copyOf(out);
    }

    private static Path bridgeDirFor(Path entry) {
        // Walk up at most 4 segments looking for a `build` parent. Typical depths:
        //   build/classes/java/main           → 3
        //   build/classes/scala/main          → 3
        //   build/resources/main              → 2
        //   build/mcdp-bridges/classes        → 2 (no-op)
        Path cur = entry;
        for (int i = 0; i < 4 && cur != null; i++) {
            Path parent = cur.getParent();
            if (parent != null && "build".equals(fileNameOrNull(parent))) {
                return parent.resolve(BRIDGE_REL_PATH);
            }
            cur = parent;
        }
        return null;
    }

    private static String fileNameOrNull(Path p) {
        Path fn = p.getFileName();
        return fn == null ? null : fn.toString();
    }
}
